"use client";
import { useEffect, useState } from "react";
const services = [["⌁","Sistemas sob medida","Plataformas digitais desenhadas para o seu fluxo, com segurança, escala e uma experiência simples."],["✦","Automação com IA","Automatizamos tarefas repetitivas e conectamos inteligência aos processos que mais consomem tempo."],["▣","Portais e presença digital","Sites e portais rápidos, acessíveis e preparados para transformar informação em relacionamento."],["⌘","Integrações e processos","Integramos sistemas, dados e equipes para reduzir retrabalho e acelerar decisões."]];
function Logo({light=false}:{light?:boolean}){return <span className={`logo ${light?"light":""}`}><span className="symbol-image-wrap"><img className="symbol-image" src="/frotatech-symbol.png" alt="" /></span><span><strong>Frota</strong><i>Tech</i><small>Soluções em tecnologia</small></span></span>}
function Arrow(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M14 7l5 5-5 5"/></svg>}
export default function Home(){const[y,setY]=useState(0),[menu,setMenu]=useState(false);useEffect(()=>{const scroll=()=>setY(scrollY);addEventListener("scroll",scroll,{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.13});document.querySelectorAll(".reveal").forEach(x=>io.observe(x));return()=>{removeEventListener("scroll",scroll);io.disconnect()}},[]);return <main>
<header className={y>30?"nav compact":"nav"}><a href="#inicio"><Logo/></a><button className="hamb" onClick={()=>setMenu(!menu)} aria-label="Abrir menu"><i/><i/></button><nav className={menu?"open":""}><a href="#servicos">Serviços</a><a href="#metodo">Como fazemos</a><a href="#sobre">Sobre</a><a className="navCta" href="#contato">Fale conosco <Arrow/></a></nav></header>
<section id="inicio" className="hero"><div className="bubble one" style={{transform:`translateY(${y*.12}px)`}}/><div className="bubble two" style={{transform:`translateY(${-y*.07}px)`}}/><div className="heroCopy"><p className="eyebrow"><i/> Tecnologia para o que vem agora</p><h1>Transformamos<br/>complexidade em<br/><em>resultados.</em></h1><p className="lead">Sistemas, automações e experiências digitais que tornam organizações mais ágeis, inteligentes e conectadas.</p><div className="actions"><a className="btn dark" href="#contato">Comece um projeto <Arrow/></a><a href="#servicos">Conheça nossas soluções ↓</a></div></div><div className="heroArt" style={{transform:`translateY(${-y*.055}px)`}}><div className="orbit"><i/><i/><i/></div><img className="mega-image" src="/frotatech-symbol.png" alt="Símbolo FrotaTech"/><aside className="card a"><small>+ EFICIÊNCIA</small><strong>Processos que fluem</strong></aside><aside className="card b"><small>IA APLICADA</small><strong>Decisões mais rápidas</strong></aside></div></section>
<div className="ticker">Estratégia <i/> Tecnologia <i/> Automação <i/> Experiência digital <i/> Resultados</div>
<section id="servicos" className="section"><div className="heading reveal"><p className="kicker">O que fazemos</p><h2>Tecnologia que trabalha<br/><em>a favor do seu negócio.</em></h2><p>Da estratégia à operação, criamos soluções digitais que resolvem desafios reais e acompanham o crescimento da sua organização.</p></div><div className="services">{services.map((s,i)=><article className="reveal" style={{transitionDelay:`${i*80}ms`}} key={s[1]}><div><span>{s[0]}</span><small>0{i+1}</small></div><h3>{s[1]}</h3><p>{s[2]}</p><a href="#contato" aria-label={`Saiba mais sobre ${s[1]}`}><Arrow/></a></article>)}</div></section>
<section id="sobre" className="impact"><div className="pattern" style={{transform:`translateY(${(y-1000)*.08}px)`}}>{Array.from({length:18}).map((_,i)=><i key={i}/>)}</div><div className="reveal"><p className="kicker">Por que a FrotaTech</p><h2>Menos atrito.<br/>Mais <em>evolução.</em></h2><p>Entendemos o contexto antes de escrever a primeira linha de código. Assim, cada solução nasce útil, sustentável e pronta para gerar impacto.</p></div><div className="metrics">{[["01","Visão estratégica e execução técnica"],["02","Soluções simples para desafios complexos"],["03","Parceria próxima em cada etapa"]].map(x=><article className="reveal" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</div></section>
<section id="metodo" className="section method"><div className="heading reveal"><p className="kicker">Nosso método</p><h2>Da ideia ao impacto,<br/><em>sem complicação.</em></h2></div><div className="steps">{[["01","Descobrir","Entendemos objetivos, pessoas e processos para encontrar a oportunidade certa."],["02","Desenhar","Transformamos estratégia em uma solução clara, intuitiva e tecnicamente sólida."],["03","Desenvolver","Construímos em ciclos curtos, com transparência, testes e evolução contínua."],["04","Evoluir","Acompanhamos resultados e melhoramos a solução conforme o negócio avança."]].map((x,i)=><article className="reveal" style={{transitionDelay:`${i*80}ms`}} key={x[0]}><span>{x[0]}</span><i/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="quote"><div className="reveal"><b>“</b><p>A melhor tecnologia é aquela que simplifica o presente e <em>abre espaço para o futuro.</em></p><Logo/></div></section>
<section id="contato" className="contact"><div className="ring"/><div className="reveal"><p className="kicker">Vamos conversar</p><h2>Seu próximo avanço<br/>começa com uma <em>boa ideia.</em></h2><p>Conte o seu desafio. A FrotaTech ajuda a transformar esse ponto de partida em uma solução que gera resultados.</p><a className="btn white" href="mailto:contato@frotatech.com.br">contato@frotatech.com.br <Arrow/></a></div></section>
<footer><Logo light/><p>© 2026 FrotaTech. Soluções em Tecnologia.</p><a href="#inicio">Voltar ao topo ↑</a></footer></main>}
